linters:
  enable:
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - revive
  - staticcheck
  - unused
  - gocritic
  - importas
  - misspell
  - revive

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
