repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict

  - repo: git://github.com/dnephin/pre-commit-golang
    rev: f780b51bd3
    hooks:
      - id: go-fmt
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
